# wrangler.toml
name = "blogshow"  # ← project name
account_id = "ace693a2998feefb0bdf639434ffd8bb"  # ← Cloudflare account id 
compatibility_date = "2024-04-01"
pages_build_output_dir = ".vercel/output/static"
functions = ".vercel/output/functions"
